<?php

/**
 * Kiosk shell strings (lane K1): the header, Done, the idle dialog, generic dialogs and the
 * generic error codes (§4.4). Lane files: signin.php (K2), learn.php (K3), learn_ui.php (K4),
 * trainer.php (K5). A key in two files is a load-time error. Plain text only ({name} placeholders).
 */

return [
    'en' => [
        'shell.brand_suffix' => 'Training',
        'shell.lang_group' => 'Language',
        'shell.lang_en' => 'English',
        'shell.lang_es' => 'Español',
        'shell.done' => 'Done',
        'shell.done_hint' => 'Sign out',
        'shell.signed_in_as' => '{name} · {dept}',
        'shell.loading' => 'Loading…',
        'shell.ok' => 'OK',
        'shell.cancel' => 'Cancel',
        'shell.yes' => 'Yes',
        'shell.no' => 'No',
        'shell.back' => 'Back',
        'shell.close' => 'Close',
        'shell.retry' => 'Try again',
        'shell.idle_title' => 'Still there?',
        'shell.idle_body' => 'For your privacy you will be signed out in {seconds} seconds.',
        'shell.idle_stay' => "I'm still here",
        'shell.idle_leave' => 'Sign out now',
        'shell.absolute_warn' => 'Your session ends in {minutes} minutes. Your progress is saved.',
        'shell.signed_out' => 'You were signed out.',
        'shell.keypad' => 'Number keypad',
        'shell.keypad_delete' => 'Delete',
        'shell.keypad_clear' => 'Clear',
        'shell.keypad_ok' => 'OK',
        'shell.keypad_status' => '{n} of {max} digits entered',
        'shell.sign_here' => 'Sign here with your finger',
        'shell.sign_clear' => 'Clear signature',
        'shell.sign_again' => 'The screen turned. Please sign again.',
        'shell.sign_name_date' => '{name} · {date}',
        'shell.not_setup_title' => 'This device is not set up for training',
        'shell.not_setup_body' => 'An administrator can set it up. Nothing is shown until then.',
        'shell.not_setup_action' => 'Set up this device (admin)',
        'shell.device_ready' => 'This device is ready: {label}',
        'shell.update_device_title' => 'Update this device',
        'shell.update_device_body' => 'This video needs a newer browser. Update the iPad (iPadOS 16.4 or later) or ask your trainer.',
        'err.validation' => 'Please check what you entered.',
        'err.session_ended' => 'Your session ended. Please sign in again.',
        'err.csrf' => 'This screen is out of date. Please try again.',
        'err.forbidden' => "That isn't allowed here.",
        'err.device_not_enrolled' => 'This device is not set up for training.',
        'err.wrong_role' => "That isn't available in this mode.",
        'err.not_found' => "We couldn't find that.",
        'err.busy' => 'Busy right now. Please try again.',
        'err.server' => 'Something went wrong. Please try again.',
        'err.network' => 'No connection. Check the Wi-Fi and try again.',
        'err.timeout' => 'That took too long. Please try again.',
        'err.rate_limited' => 'Too many tries. Please wait a minute.',
        'err.records_unavailable' => "Training records aren't available right now. Your work is saved.",
    ],
    'es' => [
        'shell.brand_suffix' => 'Capacitación',
        'shell.lang_group' => 'Idioma',
        'shell.lang_en' => 'English',
        'shell.lang_es' => 'Español',
        'shell.done' => 'Terminar',
        'shell.done_hint' => 'Cerrar sesión',
        'shell.signed_in_as' => '{name} · {dept}',
        'shell.loading' => 'Cargando…',
        'shell.ok' => 'OK',
        'shell.cancel' => 'Cancelar',
        'shell.yes' => 'Sí',
        'shell.no' => 'No',
        'shell.back' => 'Atrás',
        'shell.close' => 'Cerrar',
        'shell.retry' => 'Intentar otra vez',
        'shell.idle_title' => '¿Sigue ahí?',
        'shell.idle_body' => 'Por su privacidad, se cerrará la sesión en {seconds} segundos.',
        'shell.idle_stay' => 'Sigo aquí',
        'shell.idle_leave' => 'Cerrar sesión ya',
        'shell.absolute_warn' => 'Su sesión termina en {minutes} minutos. Su avance está guardado.',
        'shell.signed_out' => 'Se cerró su sesión.',
        'shell.keypad' => 'Teclado numérico',
        'shell.keypad_delete' => 'Borrar',
        'shell.keypad_clear' => 'Borrar todo',
        'shell.keypad_ok' => 'OK',
        'shell.keypad_status' => '{n} de {max} dígitos',
        'shell.sign_here' => 'Firme aquí con el dedo',
        'shell.sign_clear' => 'Borrar firma',
        'shell.sign_again' => 'La pantalla giró. Firme otra vez, por favor.',
        'shell.sign_name_date' => '{name} · {date}',
        'shell.not_setup_title' => 'Este dispositivo no está configurado',
        'shell.not_setup_body' => 'Un administrador lo puede configurar. No se muestra nada hasta entonces.',
        'shell.not_setup_action' => 'Configurar este dispositivo (admin)',
        'shell.device_ready' => 'Este dispositivo está listo: {label}',
        'shell.update_device_title' => 'Actualice este dispositivo',
        'shell.update_device_body' => 'Este video necesita un navegador más nuevo. Actualice el iPad (iPadOS 16.4 o más) o pregunte a su instructor.',
        'err.validation' => 'Revise lo que escribió, por favor.',
        'err.session_ended' => 'Su sesión terminó. Entre otra vez, por favor.',
        'err.csrf' => 'Esta pantalla ya no está al día. Intente otra vez.',
        'err.forbidden' => 'Eso no se permite aquí.',
        'err.device_not_enrolled' => 'Este dispositivo no está configurado para capacitación.',
        'err.wrong_role' => 'Eso no está disponible en este modo.',
        'err.not_found' => 'No lo encontramos.',
        'err.busy' => 'Está ocupado. Intente otra vez.',
        'err.server' => 'Algo salió mal. Intente otra vez.',
        'err.network' => 'No hay conexión. Revise el Wi-Fi e intente otra vez.',
        'err.timeout' => 'Tardó demasiado. Intente otra vez.',
        'err.rate_limited' => 'Demasiados intentos. Espere un minuto.',
        'err.records_unavailable' => 'Los registros de capacitación no están disponibles ahorita. Su trabajo está guardado.',
    ],
];
