<?php

namespace ITFlow\Training\Preview;

/**
 * Learner-facing UI strings for the player (EN/ES), shipped in LearnerView.strings so the
 * player (and the Phase 3 kiosk) never hard-codes text. Placeholders in braces are filled in by
 * the player: {n}, {total}, {pct}, {version}.
 */
final class PreviewStrings
{
    private const EN = [
        'preview' => 'PREVIEW',
        'draft' => 'Draft',
        'version' => 'Version {version}',
        'nothing_recorded' => 'nothing is recorded',
        'start' => 'Start',
        'continue' => 'Continue',
        'course_home' => 'Course',
        'lesson_of' => '{n} / {total}',
        'minutes' => '{n} min',
        'required' => 'Required',
        'optional' => 'Optional',
        'locked' => 'Finish the previous lesson first',
        'open_without_starting' => 'Open without starting',
        'mark_complete' => 'Mark complete & continue',
        'preview_suffix' => '(preview)',
        'back' => 'Back',
        'next' => 'Next',
        'previous' => 'Previous',
        'page_of' => 'Page {n} of {total}',
        'zoom_in' => 'Zoom in',
        'zoom_out' => 'Zoom out',
        'download' => 'Download',
        'resources' => 'Resources',
        'open_link' => 'Open link',
        'tap_to_start' => 'Tap the video to start',
        'play' => 'Play',
        'pause' => 'Pause',
        'back_10' => 'Back 10 s',
        'watched' => 'Watched {pct}%',
        'must_watch' => 'Watch at least {pct}% to continue',
        'verified' => 'Verified',
        'video_error' => "This video can't be played right now. Tell your trainer.",
        'close' => 'Close',
        'quiz_start' => 'Start quiz',
        'question_of' => 'Question {n} of {total}',
        'select_one' => 'Choose one answer',
        'select_all' => 'Select all that apply',
        'time_left' => 'Time left',
        'review' => 'Review your answers',
        'unanswered' => 'Not answered',
        'change' => 'Change',
        'submit' => 'Submit',
        'grading_authors_only' => 'Grading is available to course authors',
        'passed' => 'PASSED',
        'not_yet' => 'Not yet',
        'your_score' => 'Your score',
        'you_needed' => 'You needed {pct}%',
        'critical_missed' => 'You missed a question that must be answered correctly to pass.',
        'topics_missed' => 'Review these topics',
        'missed_questions' => 'Questions to review',
        'why' => 'Why',
        'your_choice' => 'About your answer',
        'correct_answer' => 'Correct answer',
        'retry' => 'Try again',
        'achievements' => 'Achievements unlocked',
        'ack_confirm' => 'I have read and understand this.',
        'sign_here' => 'Sign here',
        'clear' => 'Clear',
        'enter_pin' => 'Enter your PIN',
        'sign_continue' => 'Sign & continue',
        'course_complete' => 'Course complete',
        'attestation' => 'Attestation',
        'reset_progress' => 'Reset progress',
        'exit' => 'Exit',
        'language' => 'Language',
    ];

    private const ES = [
        'preview' => 'VISTA PREVIA',
        'draft' => 'Borrador',
        'version' => 'Versión {version}',
        'nothing_recorded' => 'no se registra nada',
        'start' => 'Comenzar',
        'continue' => 'Continuar',
        'course_home' => 'Curso',
        'lesson_of' => '{n} / {total}',
        'minutes' => '{n} min',
        'required' => 'Obligatorio',
        'optional' => 'Opcional',
        'locked' => 'Termine primero la lección anterior',
        'open_without_starting' => 'Abrir sin comenzar',
        'mark_complete' => 'Marcar como completada y continuar',
        'preview_suffix' => '(vista previa)',
        'back' => 'Atrás',
        'next' => 'Siguiente',
        'previous' => 'Anterior',
        'page_of' => 'Página {n} de {total}',
        'zoom_in' => 'Acercar',
        'zoom_out' => 'Alejar',
        'download' => 'Descargar',
        'resources' => 'Recursos',
        'open_link' => 'Abrir enlace',
        'tap_to_start' => 'Toque el video para comenzar',
        'play' => 'Reproducir',
        'pause' => 'Pausa',
        'back_10' => 'Atrás 10 s',
        'watched' => 'Visto {pct}%',
        'must_watch' => 'Vea al menos el {pct}% para continuar',
        'verified' => 'Verificado',
        'video_error' => 'Este video no se puede reproducir ahora. Avise a su instructor.',
        'close' => 'Cerrar',
        'quiz_start' => 'Comenzar la prueba',
        'question_of' => 'Pregunta {n} de {total}',
        'select_one' => 'Elija una respuesta',
        'select_all' => 'Seleccione todas las que correspondan',
        'time_left' => 'Tiempo restante',
        'review' => 'Revise sus respuestas',
        'unanswered' => 'Sin responder',
        'change' => 'Cambiar',
        'submit' => 'Enviar',
        'grading_authors_only' => 'La calificación está disponible para los autores del curso',
        'passed' => 'APROBADO',
        'not_yet' => 'Todavía no',
        'your_score' => 'Su puntuación',
        'you_needed' => 'Necesitaba {pct}%',
        'critical_missed' => 'Falló una pregunta que debe responderse correctamente para aprobar.',
        'topics_missed' => 'Repase estos temas',
        'missed_questions' => 'Preguntas para repasar',
        'why' => 'Por qué',
        'your_choice' => 'Sobre su respuesta',
        'correct_answer' => 'Respuesta correcta',
        'retry' => 'Intentar de nuevo',
        'achievements' => 'Logros desbloqueados',
        'ack_confirm' => 'He leído y entiendo esto.',
        'sign_here' => 'Firme aquí',
        'clear' => 'Borrar',
        'enter_pin' => 'Ingrese su PIN',
        'sign_continue' => 'Firmar y continuar',
        'course_complete' => 'Curso completado',
        'attestation' => 'Declaración',
        'reset_progress' => 'Reiniciar progreso',
        'exit' => 'Salir',
        'language' => 'Idioma',
    ];

    /** @return array<string, string> the strings for $lang (English for any other language) */
    public static function for(string $lang): array
    {
        return $lang === 'es' ? self::ES : self::EN;
    }
}
